In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.5'

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

In [6]:
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
np.where(arr % 2 != 0, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
arr.reshape(2, -1)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a, b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [10]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.concatenate([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [14]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [15]:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [17]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [18]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a, b

(array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]),
 array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8]))

In [20]:
np.intersect1d(a, b)

array([2, 4])

In [21]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [22]:
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [24]:
np.where(a == b)

(array([1, 3, 5, 7]),)

In [25]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a

array([ 2,  6,  1,  9, 10,  3, 27])

In [26]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [27]:
def maxx(x, y):
    if x >= y:
        return x
    return y
pair_max = np.vectorize(maxx)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [28]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr[:, [1, 0, -1]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [30]:
arr[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [31]:
arr[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [32]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [33]:
np.random.uniform(5, 10, (5, 3))

array([[8.33046988, 6.43746445, 6.83793511],
       [8.22181108, 8.94381459, 9.88244121],
       [9.96451744, 7.14225429, 6.1633634 ],
       [8.6342628 , 7.79916209, 6.49120626],
       [9.32544974, 9.05731097, 9.12735073]])

In [34]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.92375629, 0.9261192 , 0.46600043],
       [0.50590343, 0.07004494, 0.61005839],
       [0.60861425, 0.05814444, 0.95721392],
       [0.36650767, 0.8350482 , 0.34976811],
       [0.94010755, 0.50958128, 0.80963149]])

In [35]:
np.set_printoptions(precision=3)
rand_arr

array([[0.924, 0.926, 0.466],
       [0.506, 0.07 , 0.61 ],
       [0.609, 0.058, 0.957],
       [0.367, 0.835, 0.35 ],
       [0.94 , 0.51 , 0.81 ]])

In [36]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [37]:
np.set_printoptions(suppress=False)
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [38]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [40]:
np.set_printoptions(threshold=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.clip(a, a_min=10, a_max=30)

array([27.627, 14.64 , 21.801, 30.   , 10.   , 10.   , 30.   , 30.   ,
       10.   , 29.18 , 30.   , 11.251, 10.081, 10.   , 11.765, 30.   ,
       30.   , 10.   , 30.   , 14.43 ])

In [42]:
a.argsort()

array([ 4, 13,  5,  8, 17, 12, 11, 14, 19,  1,  2,  0,  9,  6, 16, 18,  7,
        3, 10, 15])